### ISSUE TITLE
Heading and Blockquotes

### ISSUE THREAD

**Issue by mahmoodraza** [abhibagul/Blazing-Blogger-Template#1]
Headings h1, h2, ... h6 have same font style and size.
Moreover, blockquotes are excessively indented to right due to large size of quotation mark. This seems pretty good in desktop but ugly in mobile preview.
I am not very much professional but still want to help you.
Regards

**Comment by abhibagul** [comment]
All themes are provided as is without any kind of warranty. Customization can be made on own basis.
